version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: elasticsearch8.4.2
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - network.host=0.0.0.0
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ELASTIC_PASSWORD=elasticsearchpassword
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - 'test_elasticsearch:/usr/share/elasticsearch/data'
    ports:
      - "9200:9200"
    networks:
      - test

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2
    container_name: kibana8.4.2
    restart: always
    environment:
      - network.host=0.0.0.0
      - ELASTICSEARCH_USERNAME=elasticsearch
      - ELASTICSEARCH_PASSWORD=elasticsearchpassword
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - test
volumes:
  test_elasticsearch:
      driver: local
networks:
  test:
    driver: bridge
